### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by LincCodes** [MM2-0/Kvaesitso#973] opened 2024-07-22 14:26 UTC
APP.VERSION : 1.32.0
APP.VERSIONCODE : 2024071900
APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=
LAUNCHER.APP : com.transsion.resolver
TIMEZONE : Africa/Lusaka
VERSION.RELEASE : 13
VERSION.INCREMENTAL : 240617V2390
VERSION.SDK.NUMBER : 33
BOARD : TECNO-KI5q
BOOTLOADER : unknown
BRAND : TECNO
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : KI5q-H6127AlAmAnAoApAq-T-GL-240617V2390
FINGERPRINT : TECNO/KI5q-GL/TECNO-KI5q:13/TP1A.220624.014/240617V2390:user/release-keys
HARDWARE : mt6765
HOST : buildsrv-n134
ID : TP1A.220624.014
MANUFACTURER : TECNO
MODEL : TECNO KI5q
PRODUCT : KI5q-GL
TAGS : release-keys
TIME : 1718620773000
TYPE : user![2024-07-22 16:24:53_crash.txt](https://github.com/user-attachments/files/16335262/2024-07-22.16.24.53_crash.txt)

**Comment by MM2-0** [comment] 2024-07-22 16:05
Duplicate of #967.

**Closed by MM2-0** 2024-07-22 16:05 UTC
