### ISSUE TITLE
i just use the app

### ISSUE THREAD

**Issue by Vreausexxx** [MM2-0/Kvaesitso#566] opened 2023-10-10 13:56 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=690224413, result=0, data=Intent { (has extras) }} to activity {de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: X.5da
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4977)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5018)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7563)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: X.5da
	at android.os.Parcel.readParcelableCreator(Parcel.java:3051)
[18 lines truncated]
```

## Device info
APP.VERSION : 1.27.1-fdroid<br>APP.VERSIONCODE : 2023090800<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Bucharest<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : V12.0.21.0.QCDEUXM<br>VERSION.SDK.NUMBER : 29<br>BOARD : dandelion<br>BOOTLOADER : unknown<br>BRAND : Redmi<br>CPU_ABI : armeabi-v7a<br>CPU_ABI2 : armeabi<br>DISPLAY : QP1A.190711.020<br>FINGERPRINT : Redmi/dandelion_eea/dandelion:10/QP1A.190711.020/V12.0.21.0.QCDEUXM:user/release-keys<br>HARDWARE : mt6762<br>HOST : non-pangu-pod-kw521<br>ID : QP1A.190711.020<br>MANUFACTURER : Xiaomi<br>MODEL : M2006C3LG<br>PRODUCT : dandelion_eea<br>TAGS : release-keys<br>TIME : 1677832914000<br>TYPE : user

**Comment by Vreausexxx** [comment] 2023-10-10 13:57
I dont know how it happen

**Comment by MM2-0** [comment] 2023-10-13 13:17
Duplicate of #566

**Closed by MM2-0** 2023-10-13 13:17 UTC
