### ISSUE TITLE
NullPointerException in IconService while Resolving Custom Icons in Coroutine Flow

### ISSUE THREAD

**Issue by EvanBijoy** [MM2-0/Kvaesitso#1186] opened 2024-12-23 08:10 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Stack trace

```
java.lang.NullPointerException
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invokeSuspend(IconService.kt:214)
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invoke(IconService.kt:28)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:252)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invoke(Combine.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:16)
	at kotlinx.coroutines.flow.internal.CombineKt.combineInternal(Combine.kt:21)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:78)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invoke(Merge.kt:22)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:37)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:36)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.34.0-fdroid<br>APP.VERSIONCODE : 2024120500<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 1b02e-87c13<br>VERSION.SDK.NUMBER : 34<br>BOARD : eqs<br>BOOTLOADER : MBM-3.0-eqs-c66ed235df0-240923-U1SQS34.52-21-1-13-1b02e<br>BRAND : motorola<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : U1SQS34.52-21-1-13<br>FINGERPRINT : motorola/eqs_g/eqs:14/U1SQS34.52-21-1-13/1b02e-87c13:user/release-keys<br>HARDWARE : qcom<br>HOST : ilclbld202<br>ID : U1SQS34.52-21-1-13<br>MANUFACTURER : motorola<br>MODEL : motorola edge 30 ultra<br>PRODUCT : eqs_g<br>TAGS : release-keys<br>TIME : 1727109484000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-12-23 15:14
Duplicate of #1181

**Closed by MM2-0** 2024-12-23 15:14 UTC
