### ISSUE TITLE
Search keeps crashing when entering certain letters

### ISSUE THREAD

**Issue by RebelMoogle** [MM2-0/Kvaesitso#999] opened 2024-07-27 19:30 UTC
## Description

Whenever I enter the search screen and enter 'ta' or 'ma' it crashes back to the main screen
I tried cleaning the database, restarting and clearing the cache

## Strack trace

```
java.lang.IllegalArgumentException: Key "calendar-calendar://3162" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:146)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:34)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
[76 lines truncated]
```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Los_Angeles<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 11942872<br>VERSION.SDK.NUMBER : 34<br>BOARD : husky<br>BOOTLOADER : ripcurrent-14.5-11693900<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP2A.240705.005<br>FINGERPRINT : google/husky/husky:14/AP2A.240705.005/11942872:user/release-keys<br>HARDWARE : husky<br>HOST : r-82b05a39f2cf359a-4xs6<br>ID : AP2A.240705.005<br>MANUFACTURER : Google<br>MODEL : Pixel 8 Pro<br>PRODUCT : husky<br>TAGS : release-keys<br>TIME : 1717783526000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-27 19:35
Duplicate of #962

**Closed by MM2-0** 2024-07-27 19:35 UTC
