### ISSUE TITLE
Kvaesitso not starting after the phone was turned off for long time

### ISSUE THREAD

**Issue by LitFill** [MM2-0/Kvaesitso#978] opened 2024-07-23 05:15 UTC
## Description

My phone is turned off after midnight, and automatically turned on at sunrise. this crash happens twice when i see the phone at morning. and the home aplication fallbacks to the default one.

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f16bec4, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : com.oppo.launcher<br>TIMEZONE : Asia/Jakarta<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : 2024022110<br>VERSION.SDK.NUMBER : 29<br>BOARD : oppo6765<br>BOOTLOADER : unknown<br>BRAND : OPPO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CPH2185_11_A.69<br>FINGERPRINT : OPPO/CPH2185T2/OP4F2F:10/QP1A.190711.020/2024022110:user/release-keys<br>HARDWARE : mt6765<br>HOST : ubuntu16-122-237<br>ID : QP1A.190711.020<br>MANUFACTURER : OPPO<br>MODEL : CPH2185<br>PRODUCT : CPH2185T2<br>TAGS : release-keys<br>TIME : 1708538029000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-23 07:08
Duplicate of #967

**Closed by MM2-0** 2024-07-23 07:08 UTC
