### ISSUE TITLE
Crashed once every other day

### ISSUE THREAD

**Issue by alankyshum** [MM2-0/Kvaesitso#1141] opened 2024-11-19 15:36 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 780 byte allocation with 2303312 free bytes and 2249KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.lang.Object.internalClone(Native Method)
	at java.lang.Object.clone(Object.java:267)
	at android.icu.impl.coll.CollationSettings.clone(CollationSettings.java:102)
	at android.icu.impl.coll.CollationSettings.clone(CollationSettings.java:26)
	at android.icu.impl.coll.SharedObject$Reference.copyOnWrite(SharedObject.java:140)
	at android.icu.text.RuleBasedCollator.getOwnedSettings(RuleBasedCollator.java:351)
	at android.icu.text.RuleBasedCollator.setStrength(RuleBasedCollator.java:692)
	at java.text.Collator.setStrength(Collator.java:349)
	at de.mm20.launcher2.search.SavableSearchable$DefaultImpls.compareTo(SavableSearchable.kt:31)
	at de.mm20.launcher2.applications.LauncherApp.compareTo(LauncherApp.kt:2)
	at de.mm20.launcher2.applications.LauncherApp.compareTo(LauncherApp.kt:3)
	at java.util.ComparableTimSort.binarySort(ComparableTimSort.java:262)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:207)
	at java.util.Arrays.sort(Arrays.java:1128)
[11 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Los_Angeles<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : F956U1UES1AXIB<br>VERSION.SDK.NUMBER : 34<br>BOARD : pineapple<br>BOOTLOADER : F956USQS1AXIB<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.F956U1UES1AXIB<br>FINGERPRINT : samsung/q6quew/q6q:14/UP1A.231005.007/F956U1UES1AXIB:user/release-keys<br>HARDWARE : qcom<br>HOST : SWDK6015<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-F956U1<br>PRODUCT : q6quew<br>TAGS : release-keys<br>TIME : 1727683274000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-11-19 15:44
Duplicate of #1059

**Closed by MM2-0** 2024-11-19 15:44 UTC
