### ISSUE TITLE
Stack trace, invalid sRGB value?

### ISSUE THREAD

**Issue by Doc-4** [MM2-0/Kvaesitso#805] opened 2024-05-08 07:08 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*
Nothing really notable to me, just dismissed an audio player and returned to home screen when it rebooted and dumped this log.

## Strack trace

```
java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.8146972E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.InlineClassHelperKt.throwIllegalArgumentException(InlineClassHelper.kt:3)
	at androidx.compose.ui.graphics.ColorKt.Color(Color.kt:17)
	at androidx.compose.ui.graphics.Color.copy-wmQWz5c$default(Color.kt:17)
	at de.mm20.launcher2.ui.launcher.search.common.grid.GridItemKt$ItemPopup$3.invoke(GridItem.kt:54)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:7)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:585)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:137)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:242)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:30)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:21)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:77)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:545)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
[17 lines truncated]
```

## Device info
APP.VERSION : 1.30.0<br>APP.VERSIONCODE : 2024050700<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2024050300<br>VERSION.SDK.NUMBER : 34<br>BOARD : husky<br>BOOTLOADER : ripcurrent-14.4-11403750<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 2024050300<br>FINGERPRINT : google/husky/husky:14/AP1A.240405.002.B1/2024050300:user/release-keys<br>HARDWARE : husky<br>HOST : grapheneos<br>ID : AP1A.240405.002.B1<br>MANUFACTURER : Google<br>MODEL : Pixel 8 Pro<br>PRODUCT : husky<br>TAGS : release-keys<br>TIME : 1714759413000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-05-08 16:11
Duplicate of #796

**Closed by MM2-0** 2024-05-08 16:11 UTC
