### ISSUE TITLE
NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference

### ISSUE THREAD

**Issue by salehcks** [MM2-0/Kvaesitso#417] opened 2023-06-03 02:34 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2391)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:808)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:287)
	at de.mm20.launcher2.ui.launcher.widgets.WidgetColumnKt$WidgetColumn$1$1.invokeSuspend(WidgetColumn.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:10)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1260)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1001)
	at android.view.Choreographer.doFrame(Choreographer.java:889)
[18 lines truncated]
```

## Device info
APP.VERSION : 1.24.2<br>APP.VERSIONCODE : 2023042300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : com.hihonor.android.launcher<br>TIMEZONE : Asia/Riyadh<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : 4.2.0.278C185E1R2P1<br>VERSION.SDK.NUMBER : 30<br>BOARD : CMACQ<br>BOOTLOADER : unknown<br>BRAND : HONOR<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CMA-L42CQ 4.2.0.278(C185E1R2P1)<br>FINGERPRINT : HONOR/CMA-LX2/HNCMA-Q:11/HONORCMA-L42CQ/4.2.0.278C185E1R2P1:user/release-keys<br>HARDWARE : qcom<br>HOST : cn-snxy1c-520c4b8531681462275358-c98db9766-scj45<br>ID : HONORCMA-L42CQ<br>MANUFACTURER : HONOR<br>MODEL : CMA-LX2<br>PRODUCT : CMA-LX2<br>TAGS : release-keys<br>TIME : 1681463874000<br>TYPE : user

**Comment by MM2-0** [comment] 2023-06-03 11:01
Can you please update to the latest version (1.25.1)? I believe this has been fixed already.

But also, duplicate of #195

**Closed by MM2-0** 2023-06-03 11:01 UTC
Labels: crash report
