### ISSUE TITLE
Crashes when searching certain terms (calendar related)

### ISSUE THREAD

**Issue by OxygenFrost** [MM2-0/Kvaesitso#994] opened 2024-07-26 11:37 UTC
## Description

Steps:
- Swipe down from home screen to access Kvaesitso search bar
- type "re" into search bar, either with no search filter applied or filtering for calendar
- Kvaesitso crashes

I have identified that for me, "de" and "la" also leads to a crash. Given that it seems calendar related, I tried other search strings that could relate to events in my current calendar ("de" could correspond to "dentist" or "Debbie", two events in my upcoming calendar but "la" doesn't correspond to anything obvious 

## Temporary Workaround
In Kvaesitso settings > Search, disabling "Calendar" results in search settings allows search to be used without crashes (though obviously this excludes calendar results in search results)

## Strack trace

```
java.lang.IllegalArgumentException: Key "calendar-calendar://372" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:146)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:34)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
[75 lines truncated]
```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/London<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : N976BXXS9HWHB<br>VERSION.SDK.NUMBER : 31<br>BOARD : exynos9825<br>BOOTLOADER : N976BXXS9HWHB<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SP1A.210812.016.N976BXXS9HWHB<br>FINGERPRINT : samsung/d2xeea/d2x:12/SP1A.210812.016/N976BXXS9HWHB:user/release-keys<br>HARDWARE : exynos9825<br>HOST : 21DK7B21<br>ID : SP1A.210812.016<br>MANUFACTURER : samsung<br>MODEL : SM-N976B<br>PRODUCT : d2xeea<br>TAGS : release-keys<br>TIME : 1692242995000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-26 11:38
Duplicate of #962

**Closed by MM2-0** 2024-07-26 11:38 UTC
