### ISSUE TITLE
Out of memory crash

### ISSUE THREAD

**Issue by yonatan8070** [MM2-0/Kvaesitso#1038] opened 2024-08-16 23:28 UTC
## Description

Using my phone as usual, I noticed that the home screen reloaded every time I exited an app for a few hours.
After the crash it went back to normal
I'm using a Poco F3 with CrDroid 9.6. It has 8GB of RAM.

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 1871848 free bytes and 1827KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.node.LayoutNode.applyModifier(LayoutNode.kt:36)
	at androidx.compose.ui.node.LayoutNode.setModifier(LayoutNode.kt:30)
	at androidx.compose.ui.node.ComposeUiNode$Companion$SetModifier$1.invoke(ComposeUiNode.kt:5)
	at androidx.compose.runtime.changelist.Operation$UpdateNode.execute(Operation.kt:17)
	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:23)
	at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:3)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:51)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:217)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
[12 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Jerusalem<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 1688050783<br>VERSION.SDK.NUMBER : 33<br>BOARD : kona<br>BOOTLOADER : unknown<br>BRAND : POCO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TQ3A.230605.012<br>FINGERPRINT : POCO/alioth_global/alioth:12/SKQ1.211006.001/V13.0.3.0.SKHMIXM:user/release-keys<br>HARDWARE : qcom<br>HOST : android-build<br>ID : TQ3A.230605.012<br>MANUFACTURER : Xiaomi<br>MODEL : M2012K11AG<br>PRODUCT : lineage_alioth<br>TAGS : release-keys<br>TIME : 1688050706000<br>TYPE : user

**Comment by drakegao** [comment] 2024-08-21 03:33
I think I had the similar issue, the drawer gets slower and slower and very laggy as the time goes by, but not crash yet(definitely there are some leaks), I have to reboot to solve the problem.

**Comment by MM2-0** [comment] 2024-10-20 15:53
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:53 UTC
