### ISSUE TITLE
crash on android 13.1

### ISSUE THREAD

**Issue by foss-** [MM2-0/Kvaesitso#1139] opened 2024-11-19 08:27 UTC
## Description

frequent crashes after longer usage. Sadly no specific pattern detected yet, which triggers the crash.

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 136 byte allocation with 2065064 free bytes and 2016KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.<init>(LayoutNodeLayoutDelegate.kt:10)
	at androidx.compose.ui.node.LayoutNode.<init>(LayoutNode.kt:13)
	at androidx.compose.ui.node.LayoutNode.<init>(LayoutNode.kt:3)
	at androidx.compose.ui.node.LayoutNode$Companion$Constructor$1.invoke(LayoutNode.kt:5)
	at androidx.compose.runtime.changelist.Operation$InsertNodeFixup.execute(Operation.kt:8)
	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:23)
	at androidx.compose.runtime.changelist.Operation$InsertSlotsWithFixups.execute(Operation.kt:36)
	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:23)
	at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:3)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:51)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:104)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:5)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:5)
[98 lines truncated]
```

## Device info
APP.VERSION : 1.33.1-fdroid<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 741<br>VERSION.SDK.NUMBER : 33<br>BOARD : lahaina<br>BOOTLOADER : unknown<br>BRAND : Xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TQ3A.230901.001<br>FINGERPRINT : Xiaomi/lisa/lisa:13/RKQ1.211001.001/V14.0.6.0.TKOCNXM:user/release-keys<br>HARDWARE : qcom<br>HOST : release<br>ID : TQ3A.230901.001<br>MANUFACTURER : Xiaomi<br>MODEL : 2109119DG<br>PRODUCT : lisa_global<br>TAGS : release-keys<br>TIME : 1707026526000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-11-19 15:44
Duplicate of #1059

**Closed by MM2-0** 2024-11-19 15:44 UTC
