### ISSUE TITLE
Nextcloud with self signed cert?

### ISSUE THREAD

**Issue by abonhote** [MM2-0/Kvaesitso#607] opened 2023-11-03 17:05 UTC
I keep getting "this URL does not point to a valid Nextcloud installation". I checked the code quickly and found that http gets replaced by https and finally 
`https://${url}/nextcloud/remote.php/dav` gets called. This works in Firefox when accepting the cert. Any idea how to get around this?

**Comment by Sir-Photch** [comment] 2023-11-05 23:08
Duplicate of #538

**Closed** 2023-12-17 18:44 UTC
