### ISSUE TITLE
Search Custom Icons Awful

### ISSUE THREAD

**Issue by Deadbeat13** [MM2-0/Kvaesitso#594] opened 2023-10-25 06:50 UTC
Please fix search custom icon function to freely seek through icons as search results are painfully limited when choosing alternative icons.

**Comment by Doc-4** [comment] 2023-11-09 21:08
I can note that the search often works and often doesn't. It's inconsistent. For example, I search the exact name for an icon in one of my collections, outline icons. It will not show up at all. Matching the name it has in the icon gallery app, matching the name of the package, matching the name of the app itself as displayed, all nothing. 

Another example is if I use an icon for an available app that already matches it from arcticons dark, I can see the themed versions for it, but if I want the icon as is without any theming, I have to filter for that collection and then search for it for it to actually show up as an option.

**Comment by JapanYoshi** [comment] 2024-01-27 02:11
I have an icon pack that has multiple variants for the same app (in this case, calculator). However, there seems to be no way to even see the variants within Kvaesitso.

**Comment by MM2-0** [comment] 2024-05-17 19:53
Duplicate of #757

**Closed by MM2-0** 2024-05-17 19:53 UTC
Labels: duplicate
