### ISSUE TITLE
External storage not found 

### ISSUE THREAD

**Issue by AokiAreAoki** [MM2-0/Kvaesitso#912] opened 2024-07-01 20:29 UTC
## Description

Rebooted my phone and the moment it loaded in I opened the app search bar and tried to search for an app. Apparently external storage didn't initialize in time and when I was searching launcher tried to look up things there.

## Strack trace

```
java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1196)
	at android.content.ContentResolver.query(ContentResolver.java:1117)
	at android.content.ContentResolver.query(ContentResolver.java:1073)
	at de.mm20.launcher2.files.providers.LocalFileProvider$search$2.invokeSuspend(LocalFileProvider.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2960af7, Dispatchers.Main.immediate]

```

## Device info
APP.VERSION : 1.30.4<br>APP.VERSIONCODE : 2024051000<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Kiev<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : ad9c24<br>VERSION.SDK.NUMBER : 30<br>BOARD : guamp<br>BOOTLOADER : MBM-3.0-guamp_retail-252ee94a782-220829<br>BRAND : motorola<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RPXS31.Q2-58-17-7-3<br>FINGERPRINT : motorola/guamp_retailn/guamp:11/RPXS31.Q2-58-17-7-3/ad9c24:user/release-keys<br>HARDWARE : qcom<br>HOST : ilclbld152<br>ID : RPXS31.Q2-58-17-7-3<br>MANUFACTURER : motorola<br>MODEL : moto g(9) play<br>PRODUCT : guamp_retailn<br>TAGS : release-keys<br>TIME : 1661756027000<br>TYPE : user

**Comment by Sir-Photch** [comment] 2024-07-02 05:41
Duplicate of #681

**Closed** 2024-07-03 20:52 UTC
