### ISSUE TITLE
Crash with GrapheneOS

### ISSUE THREAD

**Issue by mar0ni** [MM2-0/Kvaesitso#1016] opened 2024-08-04 07:01 UTC
```
type: crash
osVersion: google/akita/akita:14/AP2A.240705.005/2024072800:user/release-keys
package: de.mm20.launcher2.nightly:2024080200
process: de.mm20.launcher2.nightly
processUptime: 6025 + 357 ms
installer: com.android.packageinstaller

java.lang.SecurityException: Cannot get shortcuts for unrelated profile 0
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.content.pm.ILauncherApps$Stub$Proxy.getShortcuts(ILauncherApps.java:1294)
	at android.content.pm.LauncherApps.getShortcuts(LauncherApps.java:1371)
	at de.mm20.launcher2.appshortcuts.LauncherShortcutDeserializer.deserialize(AppShortcutSerialization.kt:146)
	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl.access$fromDatabaseEntity(SavableSearchableRepository.kt:151)
	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl$get$$inlined$map$1$2.emit(Emitters.kt:111)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:17)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:128)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e43b3d4, androidx.compose.runtime.BroadcastFrameClock@d96597d, StandaloneCoroutine{Cancelling}@bf66072, AndroidUiDispatcher@375fcc3]
```

**Comment by mar0ni** [comment] 2024-08-04 07:02
And then Kvaesitso keeps crashing untill I switch back to the default home app.

**Comment by MM2-0** [comment] 2024-08-15 14:44
Duplicate of #665

**Closed by MM2-0** 2024-08-15 14:44 UTC
