### ISSUE TITLE
[BUG]: Alarm counting down even when there's no alarm set

### ISSUE THREAD

**Issue by AgeusG** [MM2-0/Kvaesitso#792] opened 2024-05-06 08:11 UTC
As you can see from the attached screenshots, I don't have any alarms set to 9:30 AM or anywhere near. Weirdly enough, after it says "In 1 minute", it says "In 0 minutes" (I don't have a screenshot of this, but it did happen a few times). 

It happens also near 12:00 AM, for some reason. It might have also happened at even more times, but these are the ones I noticed so far.

I don't know what this bug is all about, but if you could fix it in the next update, that would be greatly appreciated.

Have a great day,
AgeusG

![Screenshot_20240506_093035_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/168986614/6e021ffc-62ac-4b73-923e-77dcf9e406e7)
![Screenshot_20240506_093226_Clock](https://github.com/MM2-0/Kvaesitso/assets/168986614/1b676311-4b6b-4cbf-9d51-d906174052ce)

**Comment by JetpackJackson** [comment] 2024-07-22 12:13
I'm also having this bug.

**Comment by MM2-0** [comment] 2024-10-20 15:59
Duplicate of #172

**Closed by MM2-0** 2024-10-20 15:59 UTC
