### ISSUE TITLE
[Feature Request] Copy Search

### ISSUE THREAD

**Issue by iDutchy** [MM2-0/Kvaesitso#324] opened 2023-04-04 09:30 UTC
So I really love the search with this launcher, but currently when you want to use the calculator, converter, etc. you need to remember the result if you need to use it somewhere. Would love to see a feature being added where you can like long press a result to copy.

**Comment by MM2-0** [comment] 2023-04-04 09:47
Duplicate of #300

**Closed by MM2-0** 2023-04-04 09:47 UTC
