### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AdityaMH** [MM2-0/Kvaesitso#1131] opened 2024-11-10 08:29 UTC
## Description

Crash

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 786080 free bytes and 767KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(GraphicsLayerOwnerLayer.android.kt:33)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.mapBounds(GraphicsLayerOwnerLayer.android.kt:23)
	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:74)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:196)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap(SemanticsUtils.android.kt:65)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes(AndroidComposeViewAccessibilityDelegateCompat.android.kt:19)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:72)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$ComposeAccessibilityNodeProvider.createAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:8)
	at androidx.core.view.accessibility.AccessibilityNodeProviderCompat$AccessibilityNodeProviderApi19.createAccessibilityNodeInfo(AccessibilityNodeProviderCompat.java:3)
	at android.view.AccessibilityInteractionController.populateAccessibilityNodeInfoForView(AccessibilityInteractionController.java:427)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:363)
[10 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 240416V4104<br>VERSION.SDK.NUMBER : 33<br>BOOTLOADER : unknown<br>CPU_ABI : arm64-v8a<br>TAGS : release-keys<br>TIME : 1713279477000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-11-10 16:30
Duplicate of #1059

**Closed by MM2-0** 2024-11-10 16:30 UTC
