### ISSUE TITLE
Reporting if useful

### ISSUE THREAD

**Issue by drAndric** [MM2-0/Kvaesitso#499] opened 2023-08-20 13:14 UTC
I wasn't doing anything on the home screen, so no idea how to reproduce it

**Comment by drAndric** [comment] 2023-08-20 13:18
android.os.DeadSystemRuntimeException: android.os.DeadSystemException
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1442)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1417)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1412)
	at de.mm20.launcher2.music.MusicServiceImpl$getInstalledPlayerPackages$2.invokeSuspend(MusicService.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e97f51c, Dispatchers.Default]
Caused by: android.os.DeadSystemException
	... 9 more

**Comment by MM2-0** [comment] 2023-10-13 13:27
Duplicate of #546

**Closed by MM2-0** 2023-10-13 13:27 UTC
Labels: duplicate, crash report
