### ISSUE TITLE
[Issue] The app drawer scroll feels choppy 

### ISSUE THREAD

**Issue by SoaibHaque** [MM2-0/Kvaesitso#309] opened 2023-04-01 11:18 UTC
When I swipe down, the search bar and the app drawer opens up but the UX is so choppy. When I scrolling on the app drawer Its feels like It's skips some frames or the animation is so much laggy. And when I swipe down, the keyboard opens up too because of the focus on the search bar it's very annoying. Can you give a option to set the swipe up with search focus and one without focus. And please fix the choppiness of thr app drawer. Other than that I really like this app.

**Comment by egayghost** [comment] 2023-04-01 11:51
I can confirm it here as well, it's choppy most of the time when scrolling

**Comment by MM2-0** [comment] 2023-04-01 13:58
Duplicate of #257

**Closed by MM2-0** 2023-04-01 13:58 UTC
