### ISSUE TITLE
Recorded bug report

### ISSUE THREAD

**Issue by hsfchris** [MM2-0/Kvaesitso#1124] opened 2024-11-03 19:05 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

I honestly didn't notice anything wrong, just the bug report popping up on my screen. Here you go.

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 2440080 free bytes and 2382KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(GraphicsLayerOwnerLayer.android.kt:55)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.mapBounds(GraphicsLayerOwnerLayer.android.kt:23)
	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:74)
	at androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf(NodeCoordinator.kt:79)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:104)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap$findAllSemanticNodesRecursive(SemanticsUtils.android.kt:294)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.getAllUncoveredSemanticsNodesToIntObjectMap(SemanticsUtils.android.kt:65)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes(AndroidComposeViewAccessibilityDelegateCompat.android.kt:19)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$scheduleScrollEventIfNeeded$1.invoke(AndroidComposeViewAccessibilityDelegateCompat.android.kt:75)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
[62 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 15<br>VERSION.INCREMENTAL : 12366759<br>VERSION.SDK.NUMBER : 35<br>BOARD : shiba<br>BOOTLOADER : ripcurrent-15.0-12059390<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP3A.241005.015<br>FINGERPRINT : google/shiba/shiba:15/AP3A.241005.015/12366759:user/release-keys<br>HARDWARE : shiba<br>HOST : r-68354e84479a5a03-9kd0<br>ID : AP3A.241005.015<br>MANUFACTURER : Google<br>MODEL : Pixel 8<br>PRODUCT : shiba<br>TAGS : release-keys<br>TIME : 1726248772000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-11-04 10:35
Duplicate of #1059

**Closed by MM2-0** 2024-11-04 10:35 UTC
