### ISSUE TITLE
crash on memory allocation 

### ISSUE THREAD

**Issue by mrotschi** [MM2-0/Kvaesitso#1066] opened 2024-08-30 19:09 UTC
## Description

I was not doing something special. At some point, the scroll on the main screen was very slow but it was one hour or so before the crash report.

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 851768 free bytes and 831KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(GraphicsLayerOwnerLayer.android.kt:316)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.mapBounds(GraphicsLayerOwnerLayer.android.kt:23)
	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:74)
	at androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf(NodeCoordinator.kt:79)
	at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:31)
	at de.mm20.launcher2.ui.launcher.search.common.grid.GridItemKt$$ExternalSyntheticLambda4.invoke(R8$$SyntheticClass:41)
	at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:66)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Paris<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : gms-d57debf7<br>VERSION.SDK.NUMBER : 33<br>BOARD : FP3<br>BOOTLOADER : unknown<br>BRAND : Fairphone<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 6.A.030.0<br>FINGERPRINT : Fairphone/FP3/FP3:13/6.A.030.0/gms-d57debf7:user/release-keys<br>HARDWARE : qcom<br>HOST : jenkins-agent-01<br>ID : 6.A.030.0<br>MANUFACTURER : Fairphone<br>MODEL : FP3<br>PRODUCT : FP3<br>TAGS : release-keys<br>TIME : 1721420902000<br>TYPE : user

**Comment by noesterle** [comment] 2024-10-07 17:30
I've experienced this crash and error as well.

## Description

Not doing anything in particular, just scrolling around and opening and dismissing the app drawer. The UI slows down over time until it crashes. Once it recovers from the crash, the UI is as smooth and fluid as expected.

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 137408 free bytes and 134KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.view.InsetsState$1.createFromParcel(InsetsState.java:791)
	at android.view.InsetsState$1.createFromParcel(InsetsState.java:788)
	at android.os.Parcel.readTypedObject(Parcel.java:4159)
	at android.view.IWindow$Stub.onTransact(IWindow.java:268)
	at android.os.Binder.execTransactInternal(Binder.java:1505)
	at android.os.Binder.execTransact(Binder.java:1444)

```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 12235381<br>VERSION.SDK.NUMBER : 34<br>BOARD : raven<br>BOOTLOADER : slider-14.5-12088207<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP2A.240905.003.F1<br>FINGERPRINT : google/raven/raven:14/AP2A.240905.003.F1/12235381:user/release-keys<br>HARDWARE : raven<br>HOST : r-68354e84479a5a03-l46s<br>ID : AP2A.240905.003.F1<br>MANUFACTURER : Google<br>MODEL : Pixel 6 Pro<br>PRODUCT : raven<br>TAGS : release-keys<br>TIME : 1723754412000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-10-20 15:55
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:55 UTC
