### ISSUE TITLE
Got really slow on the home page and then crashed. 

### ISSUE THREAD

**Issue by ynyz** [MM2-0/Kvaesitso#1036] opened 2024-08-16 03:08 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

I can tell when it's about to crash. it's gradual. It starts where there is a slight delay between my swipe and the response from the launcher. The delay gets more frequent and more intense over time. eventually it becomes almost unresponsive. then it does become completely unresponsive. then, It crashes. it's happened a couple times before. restarting the device seems to fix it. restarting the launcher would probably also fix it. idk much about technical stuff, but for some reason I assume it's a memory leak?? 

## Strack trace

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.Default, Continuation at de.mm20.launcher2.ui.launcher.search.SearchVM$search$1$1$1$resultsList$1.invokeSuspend(SearchVM.kt)@8f73927]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:40)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:173)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [DispatchedCoroutine{Cancelling}@3d33472, Dispatchers.Default]
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 301936 free bytes and 294KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.String.fastSubstring(Native Method)
	at java.lang.String.substring(String.java:2489)
	at java.lang.Class.getSimpleName(Class.java:1907)
	at kotlinx.coroutines.JobSupport.getCancellationException(JobSupport.kt:24)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:82)
	... 1 more

```

## Device info
APP.VERSION : 1.31.2<br>APP.VERSIONCODE : 2024070300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 12025142<br>VERSION.SDK.NUMBER : 34<br>BOARD : panther<br>BOOTLOADER : cloudripper-14.5-11677884<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP2A.240805.005<br>FINGERPRINT : google/panther/panther:14/AP2A.240805.005/12025142:user/release-keys<br>HARDWARE : panther<br>HOST : r-82b05a39f2cf359a-g5s4<br>ID : AP2A.240805.005<br>MANUFACTURER : Google<br>MODEL : Pixel 7<br>PRODUCT : panther<br>TAGS : release-keys<br>TIME : 1719515769000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-10-20 15:53
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:53 UTC
