### ISSUE TITLE
Crash report happened scrolling

### ISSUE THREAD

**Issue by Gedaliya** [MM2-0/Kvaesitso#83] opened 2022-05-27 16:48 UTC
## Description

Happened when rapidly opening the drawer and scrolling with keyboard open. Not able to reproduce

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalStateException: Offset is unspecified
	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:67)
	at androidx.compose.ui.geometry.Offset.minus-MK-Hz9U(Offset.kt:168)
	at androidx.compose.ui.input.pointer.PointerEventKt.positionChangeInternal(PointerEvent.kt:814)
	at androidx.compose.ui.input.pointer.PointerEventKt.positionChangeIgnoreConsumed(PointerEvent.kt:808)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt.verticalDrag-jO51t88(DragGestureDetector.kt:374)
	at androidx.compose.foundation.gestures.DragGestureDetectorKt$verticalDrag$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:560)
[63 lines truncated]
```

## Device info
APP.VERSION : 1.10.1-20220518<br>APP.VERSIONCODE : 2022051800<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/Chicago<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 8353555<br>VERSION.SDK.NUMBER : 32<br>BOARD : barbet<br>BOOTLOADER : b9-0.4-8048809<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SP2A.220505.002<br>FINGERPRINT : google/barbet/barbet:12/SP2A.220505.002/8353555:user/release-keys<br>HARDWARE : barbet<br>HOST : abfarm788<br>ID : SP2A.220505.002<br>MANUFACTURER : Google<br>MODEL : Pixel 5a<br>PRODUCT : barbet<br>TAGS : release-keys<br>TIME : 1648149098000<br>TYPE : user

**Comment by MM2-0** [comment] 2022-06-12 17:28
Duplicate of #81

**Closed by MM2-0** 2022-06-12 17:28 UTC
