### ISSUE TITLE
It keeps crashing 

### ISSUE THREAD

**Issue by Shinigami-pixel** [MM2-0/Kvaesitso#946] opened 2024-07-12 13:02 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.launcher.searchbar.SearchBarMenuKt$SearchBarMenu$4$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:42)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[59 lines truncated]
```

## Device info
APP.VERSION : 1.31.2<br>APP.VERSIONCODE : 2024070300<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Africa/Lagos<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : OP-V127-20230810<br>VERSION.SDK.NUMBER : 30<br>BOARD : X6511B<br>BOOTLOADER : unknown<br>BRAND : Infinix<br>CPU_ABI : armeabi-v7a<br>CPU_ABI2 : armeabi<br>DISPLAY : X6511B-F6318-11.0-OP-V127-20230810<br>FINGERPRINT : Infinix/F6318/Infinix-X6511B:11/RP1A.201005.001/OP-V127-20230810:user/release-keys<br>HARDWARE : X6511B<br>HOST : buildsrv-cq12<br>ID : RP1A.201005.001<br>MANUFACTURER : INFINIX MOBILITY LIMITED<br>MODEL : Infinix X6511B<br>PRODUCT : F6318<br>TAGS : release-keys<br>TIME : 1691664777000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-12 18:04
Duplicate of #937

**Closed by MM2-0** 2024-07-12 18:04 UTC
