### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tuanmanh141196** [MM2-0/Kvaesitso#935] opened 2024-07-09 03:28 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 1289384 free bytes and 1259KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.os.Parcel.readBundle(Parcel.java:3371)
	at android.os.Parcel.readBundle(Parcel.java:3354)
	at android.os.Message.readFromParcel(Message.java:660)
	at android.os.Message.-$$Nest$mreadFromParcel(Unknown Source:0)
	at android.os.Message$1.createFromParcel(Message.java:612)
	at android.os.Message$1.createFromParcel(Message.java:609)
	at android.os.Parcel.readTypedObject(Parcel.java:4037)
	at android.os.IMessenger$Stub.onTransact(IMessenger.java:85)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1311)

```

## Device info
APP.VERSION : 1.31.2<br>APP.VERSIONCODE : 2024070300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Ho_Chi_Minh<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S908EXXS7DWL1<br>VERSION.SDK.NUMBER : 34<br>BOARD : taro<br>BOOTLOADER : S908EXXS7DWL1<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.S908EXXS7DWL1<br>FINGERPRINT : samsung/b0qxxx/b0q:14/UP1A.231005.007/S908EXXS7DWL1:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DKG907<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-S908E<br>PRODUCT : b0qxxx<br>TAGS : release-keys<br>TIME : 1701689242000<br>TYPE : user

**Comment by RahulMJ5** [comment] 2024-09-30 14:45
Hey, I am facing the same issue on production.
Any Lead?

**Comment by MM2-0** [comment] 2024-10-20 15:54
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:54 UTC
