### ISSUE TITLE
Crash on reboot

### ISSUE THREAD

**Issue by AIM-less** [MM2-0/Kvaesitso#857] opened 2024-05-23 06:38 UTC
## Description

After rebooting the device ,I was notified that the app crashed, then I just relaunched without troubles
Still the nicest launcher for me though 

## Strack trace

```
java.lang.IllegalArgumentException: Volume external_primary not found
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1221)
	at android.content.ContentResolver.query(ContentResolver.java:1153)
	at android.content.ContentResolver.query(ContentResolver.java:1109)
	at de.mm20.launcher2.files.providers.LocalFileProvider$search$2.invokeSuspend(LocalFileProvider.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e9ee2be, Dispatchers.Main.immediate]

```

## Device info
APP.VERSION : 1.30.4<br>APP.VERSIONCODE : 2024051000<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 1169<br>VERSION.SDK.NUMBER : 31<br>BOARD : ums9230_nico<br>BOOTLOADER : unknown<br>BRAND : realme<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RMX3511PU_12_C.24<br>FINGERPRINT : realme/RMX3511/RE87BAL1:12/SP1A.210812.016/R.202303101620:user/release-keys<br>HARDWARE : ums9230_nico<br>HOST : ubuntu-143-182<br>ID : SP1A.210812.016<br>MANUFACTURER : realme<br>MODEL : RMX3511<br>PRODUCT : RMX3511<br>TAGS : release-keys<br>TIME : 1678437326000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-05-23 20:16
Duplicate of #681

**Closed by MM2-0** 2024-05-23 20:16 UTC
