### ISSUE TITLE
App List has square edges

### ISSUE THREAD

**Issue by carlin978** [MM2-0/Kvaesitso#815] opened 2024-05-10 07:03 UTC
The app list has square edges when it shouldn't.
Changing the appearance settings doesn't have an effect.![Screenshot_20240510-075220.png](https://github.com/MM2-0/Kvaesitso/assets/120719190/67e3bb3f-aa9a-4b10-b5f6-8524e53aab83)

Kvaesitso 1.30.3
Android 10
Device: Alcatel 1SE 2020

**Comment by exstntlmsnthrp** [comment] 2024-05-10 11:49
I'm using the same app version (albeit with Android 14) and cannot reproduce this issue. 

![Screenshot_20240510-074810.png](https://github.com/MM2-0/Kvaesitso/assets/57594290/b9b1e62c-98f6-4e75-9a4a-03c1b1ee9b03)

**Comment by carlin978** [comment] 2024-05-11 13:40
No, it did not have an effect.
None of the appearance settings had an effect. I genuinely believe this is a bug caused by some change made in a recent release.
I don't know if it's an issue caused by my older version of Android or something else, but it did work before.
I might try to downgrade Kvaesitso to pinpoint what version caused the problem.

**Comment by exstntlmsnthrp** [comment] 2024-05-12 12:44
My guess is that's related to the version of Android. I know there were pretty substantive UI changes from a code perspective in both version 11 and specifically in version 12. 

If it were a bug in kvaesitso,I would have expected more people to report it. But who knows, I've not been able to replicate it.

**Comment by OmegaSunkey** [comment] 2024-05-15 15:04
Seems that the only way to replicate that bug is to make it have a cold start. Try force-closing and opening the launcher again. Telling because this happened to me accidentally while trying to catch another bug.

**Comment by OmegaSunkey** [comment] 2024-05-15 17:19
Reinstalled Kvaesitso because of signature mismatch (why?) and still happens.
![Screenshot_20240515-121408_Kvaesitso](https://github.com/MM2-0/Kvaesitso/assets/94485936/1474c6d2-c4f9-46a8-af3a-854abbd99c74)
This is version 1.30.4

**Comment by exstntlmsnthrp** [comment] 2024-05-19 12:40
You get a signature mismatch because different repositories use different build signatures for the APK. I would assume, here on GitHub, the developer uses their own signing key for the APK. Then on izzyondroid they use their own signing key when they build the APK. If the app goes on the Play Store, there's yet another, different signing key used for that. So if someone tries to update the app from a different source from which they originally installed it, there is a key mismatch and it cannot be updated from that source without reinstalling the app. I hope that helps. 

Back to your problem. I am still unable to duplicate the problem. I've forced the app to stop and restarted and I've switched to a different home app and back again and I still have rounded corners as in my screenshot above. 

Can you go to app settings and share the logs so the dev can take a look to see if they can find anything?

**Comment by carlin978** [comment] 2024-07-02 12:57
Most recent version fixed the problem

**Closed** 2024-07-02 12:58 UTC
