### ISSUE TITLE
Smartspacer widget doesn't work

### ISSUE THREAD

**Issue by Merlin04** [MM2-0/Kvaesitso#688] opened 2024-02-08 20:05 UTC
When I try to add the Smartspacer widget, nothing happens - after I configure the widget and tap apply, I get sent back to the "select a widget to add" screen. I've tested it in other launchers and it works fine, so it seems like a Kvaesitso issue.

**Comment by MM2-0** [comment] 2024-02-10 14:12
Related #658

**Comment by MM2-0** [comment] 2024-02-10 14:14
Duplicate of #582

**Closed by MM2-0** 2024-02-10 14:14 UTC
Labels: bug
