### ISSUE TITLE
App crash after used for couple days

### ISSUE THREAD

**Issue by robert0ng** [MM2-0/Kvaesitso#1113] opened 2024-10-20 23:28 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 72 byte allocation with 1577040 free bytes and 1540KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3553)
	at java.util.Arrays.copyOf(Arrays.java:3522)
	at java.util.ArrayList.grow(ArrayList.java:244)
	at java.util.ArrayList.grow(ArrayList.java:251)
	at java.util.ArrayList.add(ArrayList.java:461)
	at java.util.ArrayList.add(ArrayList.java:474)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:44)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.fillOneLayerOfSemanticsWrappers(SemanticsNode.kt:48)
	at androidx.compose.ui.semantics.SemanticsNode.unmergedChildren$ui_release(SemanticsNode.kt:15)
	at androidx.compose.ui.semantics.SemanticsNode.getChildren$ui_release(SemanticsNode.kt:27)
[20 lines truncated]
```

## Device info
APP.VERSION : 1.33.1-fdroid<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Taipei<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : eng.compil.20240902.172845<br>VERSION.SDK.NUMBER : 34<br>BOARD : k6983v1_64<br>BOOTLOADER : unknown<br>BRAND : vivo<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : PD2183F_EX_A_14.2.15.1.W20.V000L1<br>FINGERPRINT : vivo/V2144/V2144:14/UP1A.231005.007/compiler09021725:user/release-keys<br>HARDWARE : mt6983<br>HOST : comdg01146223<br>ID : UP1A.231005.007<br>MANUFACTURER : vivo<br>MODEL : V2144<br>PRODUCT : V2144<br>TAGS : release-keys<br>TIME : 1725269144000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-10-21 06:16
Duplicate of #1059

**Closed by MM2-0** 2024-10-21 06:16 UTC
