### ISSUE TITLE
Buggy ui

### ISSUE THREAD

**Issue by Underday** [MM2-0/Kvaesitso#304] opened 2023-03-26 09:35 UTC
Concept is really great but ui is so buggy for me, IDK why but launcher is useless with this issue

**Comment by exstntlmsnthrp** [comment] 2023-03-26 13:40
As it is written, this is not a bug. This is simply a personal complaint. 

Please update this with actual information, screenshots, etc, that clearly describe the problems you feel exist and ways for others to try to duplicate them. Include your phone model, Android version, and app version at minimum. 

Otherwise, this is simply a personal rant and useless for anyone, and should be closed by @MM2-0.

**Closed** 2023-03-27 21:49 UTC
