### ISSUE TITLE
Enter button press on keyboard opens the first search result

### ISSUE THREAD

**Issue by sandorfimarci** [MM2-0/Kvaesitso#190] opened 2022-10-21 08:33 UTC
When searching for an app, after the type when user press the enter button on the keyboard, the first search result could be open.

Reproduce:
1. Search for an app
2. When there is result (there is an app which match with the query) press the enter button

Requested behavior:
Open the first search result

Current behavior:
Nothing happens. Have to click on the app.

(When there is no search result, a search could be launch with the given query in google (or in the preferred/first search engine in the list))

**Comment by MM2-0** [comment] 2022-11-06 13:16
Duplicate of #53

**Closed by MM2-0** 2022-11-06 13:16 UTC
