### ISSUE TITLE
IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}

### ISSUE THREAD

**Issue by Doc-4** [MM2-0/Kvaesitso#1018] opened 2024-08-04 19:30 UTC
## Description

This happens when I try to remove an app called Yatse from media integration. Even if it doesn't crash, it can't seem to successfully remove it as it's there when reopened.

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.component.preferences.PreferenceScreenKt$PreferenceScreen$3$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:5)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[63 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2024072800<br>VERSION.SDK.NUMBER : 34<br>BOARD : husky<br>BOOTLOADER : ripcurrent-14.5-11693900<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 2024072800<br>FINGERPRINT : google/husky/husky:14/AP2A.240705.005/2024072800:user/release-keys<br>HARDWARE : husky<br>HOST : grapheneos<br>ID : AP2A.240705.005<br>MANUFACTURER : Google<br>MODEL : Pixel 8 Pro<br>PRODUCT : husky<br>TAGS : release-keys<br>TIME : 1722207829000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-08-11 20:15
Duplicate of #937

**Closed by MM2-0** 2024-08-11 20:15 UTC
Labels: crash report
