### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fsociety-spider** [MM2-0/Kvaesitso#979] opened 2024-07-23 11:51 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5cf2619, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : V12.5.1.0.RFKINXM<br>VERSION.SDK.NUMBER : 30<br>BOARD : raphaelin<br>BOOTLOADER : unknown<br>BRAND : Xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RKQ1.200826.002 test-keys<br>FINGERPRINT : Xiaomi/raphaelin/raphaelin:11/RKQ1.200826.002/V12.5.1.0.RFKINXM:user/release-keys<br>HARDWARE : qcom<br>HOST : c5-miui-ota-bd254.bj<br>ID : RKQ1.200826.002<br>MANUFACTURER : Xiaomi<br>MODEL : Redmi K20 Pro<br>PRODUCT : raphaelin<br>TAGS : release-keys<br>TIME : 1624895488000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-23 11:53
Duplicate of #967

**Closed by MM2-0** 2024-07-23 11:53 UTC
