### ISSUE TITLE
Feature request: taskbar/quickswitch (app) support. 

### ISSUE THREAD

**Issue by luminax10** [MM2-0/Kvaesitso#1148] opened 2024-11-27 10:25 UTC
On Android 12L+ (or 13+ idk) Is it possible to add support for taskbar and recents replacing (via quick switch app) to kvaesitso?

I love the taskbar in AOSP Android, but it has problem with launchers (it minimizes itself when using different launchers) so if kvaesitso adding that option, I'll be REALLY HAPPY.

**Comment by MM2-0** [comment] 2024-11-27 15:01
Duplicate of #5

**Closed by MM2-0** 2024-11-27 15:01 UTC

**Comment by luminax10** [comment] 2024-11-27 15:52
So it's very hard and not worth it, sad.
