### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yant0** [MM2-0/Kvaesitso#981] opened 2024-07-23 14:42 UTC
## Description

random, usually from exiting / entering recent apps view

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'int com.android.server.wm.Task.mTaskId' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.content.pm.ILauncherApps$Stub$Proxy.startActivityAsUser(ILauncherApps.java:1146)
	at android.content.pm.LauncherApps.startMainActivity(LauncherApps.java:745)
	at de.mm20.launcher2.applications.LauncherApp.launch(LauncherApp.kt:49)
	at de.mm20.launcher2.ui.launcher.search.common.SearchableItemVM.launch(SearchableItemVM.kt:85)
	at de.mm20.launcher2.ui.launcher.search.common.grid.GridItemKt$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:39)
	at androidx.compose.foundation.CombinedClickableNodeImpl$clickPointerInput$5.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(TapGestureDetector.kt:329)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
[67 lines truncated]
```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Jakarta<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : eng.kvije6.20220928.173228<br>VERSION.SDK.NUMBER : 30<br>BOARD : sdm636<br>BOOTLOADER : unknown<br>BRAND : asus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RQ3A.211001.001<br>FINGERPRINT : google/raven/raven:13/TP1A.220905.004/8927612:user/release-keys<br>HARDWARE : qcom<br>HOST : harshainstance-1<br>ID : RQ3A.211001.001<br>MANUFACTURER : asus<br>MODEL : Zenfone Max Pro M1<br>PRODUCT : WW_X00T<br>TAGS : release-keys<br>TIME : 1664386346000<br>TYPE : user

**Comment by yant0** [comment] 2024-07-23 14:44
+ this happens quite alot & sometimes its from different cause, last crash i remember was because my phone is muted / 0 volume

**Comment by MM2-0** [comment] 2024-08-11 20:39
Duplicate of #74

**Closed by MM2-0** 2024-08-11 20:39 UTC
