### ISSUE TITLE
Unremovable date widget in clock on home screen

### ISSUE THREAD

**Issue by Mokura** [MM2-0/Kvaesitso#265] opened 2023-02-21 22:02 UTC
After updating to 1.22.2, a text date widget appears underneath the clock, regardless of whether the pinned row of favorites is enabled or not.  Pixel 3a, LineageOS 19.1 (A12).

**Comment by Sir-Photch** [comment] 2023-02-22 09:10
This is intended behavior. This date-part dynamically switches to other elements (music playing, battery level) when required (depending on your settings). 
The favorites are now always shown when enabled.

**Comment by Mokura** [comment] 2023-02-22 14:57
I'd like to (low-priority) request a toggle for that particular line, then - at least in my case I check the date via QS pulldown, or putting a date & time widget in the swipe up area.  It looks a little jarring with the binary clock, but that's just my own opinion.

**Comment by anomopoda** [comment] 2023-02-22 16:34
Agreed - would love the option to hide the date if possible!

**Comment by nv2p** [comment] 2023-02-24 12:01
Yep, me too! Until now, although I didn't see why this widget was compulsory, it didn't bother me, as I was able to have it "invisible" somehow, by choosing the right type of clock. Now, it pushes my 3 row of favorites too much down... ;P

**Comment by Sir-Photch** [comment] 2023-02-24 17:02
Well I see that with the big digital clock, it is a tad bit too much. Maybe try the compact layout then, or another clock? In any case, I don't think it'd be too complicated to add another switch to turn off the date part and make that additional row disappear then.

**Comment by MM2-0** [comment] 2023-02-24 17:25
> In any case, I don't think it'd be too complicated to add another switch to turn off the date part and make that additional row disappear then.

Already done ;)

Closed in d54b904

**Closed by MM2-0** 2023-02-24 17:25 UTC
