### ISSUE TITLE
Slow performance, lagging

### ISSUE THREAD

**Issue by Drsheppard01** [MM2-0/Kvaesitso#875] opened 2024-06-06 08:01 UTC
## Description

Looks like out of memory issue

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 2662064 free bytes and 2599KB until OOM, target footprint 402653184, growth limit 402653184; giving up on allocation because <1% of heap free after GC.
	at libcore.util.NativeAllocationRegistry.registerNativeAllocation(NativeAllocationRegistry.java:270)
	at android.graphics.Path.<init>(Path.java:65)
	at androidx.compose.ui.graphics.AndroidPath.<init>(AndroidPath.android.kt:3)
	at androidx.compose.ui.graphics.AndroidPath_androidKt.Path(AndroidPath.android.kt:4)
	at androidx.compose.ui.graphics.vector.PathComponent.<init>(Vector.kt:32)
	at androidx.compose.ui.graphics.vector.VectorPainterKt.createGroupComponent(VectorPainter.kt:25)
	at androidx.compose.ui.graphics.vector.VectorPainterKt.rememberVectorPainter(VectorPainter.kt:57)
	at androidx.compose.material3.IconKt.Icon-ww6aTOc(Icon.kt:9)
	at de.mm20.launcher2.ui.component.weather.AnimatedWeatherIconKt.Cold(AnimatedWeatherIcon.kt:106)
	at de.mm20.launcher2.ui.component.weather.AnimatedWeatherIconKt.AnimatedWeatherIcon(AnimatedWeatherIcon.kt:304)
	at de.mm20.launcher2.ui.launcher.widgets.weather.WeatherWidgetKt.CurrentWeather(WeatherWidget.kt:845)
	at de.mm20.launcher2.ui.launcher.widgets.weather.WeatherWidgetKt.WeatherWidget(WeatherWidget.kt:506)
	at de.mm20.launcher2.ui.launcher.widgets.WidgetItemKt$WidgetItem$6$1$2.invoke(WidgetItem.kt:31)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:19)
[40 lines truncated]
```

## Device info
APP.VERSION : 1.30.4<br>APP.VERSIONCODE : 2024051000<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Moscow<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : T.R4T3.1781f31-1-2<br>VERSION.SDK.NUMBER : 34<br>BOARD : k6983v1_64<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CPH2493_14.0.0.510(EX01)<br>FINGERPRINT : OnePlus/CPH2493/OP556FL1:14/UKQ1.230924.001/T.R4T3.1781f31-1-2:user/release-keys<br>HARDWARE : mt6983<br>HOST : dg02-pool06-kvm50<br>ID : UKQ1.230924.001<br>MANUFACTURER : OnePlus<br>MODEL : CPH2493<br>PRODUCT : CPH2493<br>TAGS : release-keys<br>TIME : 1712546554000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment] 2024-06-06 14:05
This looks like a duplicate of #823.

**Comment by MM2-0** [comment] 2024-10-20 15:54
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:54 UTC
