### ISSUE TITLE
App Drawer scroll isnt smooth

### ISSUE THREAD

**Issue by abdul2801** [MM2-0/Kvaesitso#555] opened 2023-09-27 06:38 UTC
Video for reference -> 

https://github.com/MM2-0/Kvaesitso/assets/74723091/e59bd924-5e99-4257-8362-05648f11a326

Needs some optimization

**Comment by kumail-r** [comment] 2023-10-11 17:37
It was completely smooth for me running GrapheneOS on a Pixel 7, but after restarting to install an Android update this morning it stutters quite heavily when the app drawer is opened. I have not installed any apps or otherwise used my phone to do anything other than update Android, it was working smoothly for me as of yesterday (seemed to be locked to 90hz, but I did not measure it so I can't be certain).

**Comment by jjpebesma** [comment] 2023-10-11 21:23
Same situation as @kumail-r .  I am using a Google Pixel 6 also with GrapheneOS. After an update this morning the app drawer is stuttering quite a lot. Other apps seem fine.

**Comment by yaomtc** [comment] 2023-10-12 00:30
Pixel 6a, GrapheneOS, have performance issues with this launcher as of the most recent stable update of GOS. I might create an issue over there.

**Comment by theamazing0** [comment] 2023-10-14 15:35
Reinstalling fixes the issue, but with all the GrapheneOS releases, its getting annoying.

**Comment by theamazing0** [comment] 2023-10-14 15:45
I think this is a duplicate of #529

**Comment by dtomvan** [comment] 2023-10-14 16:33
Nope, #257

**Comment by gromoslaw-kroczka** [comment] 2023-10-15 08:09
I've got similar issue with PixelOS on Android 13. Just trying this Launcher from today, so cannot say how it behave earlier.

**Comment by theamazing0** [comment] 2023-11-02 00:21
Still happening for me on OS update, are there any logs that could help?

**Closed** 2024-12-15 12:39 UTC
