### ISSUE TITLE
[Bug] Keyboard crashing when searching and switching languages.

### ISSUE THREAD

**Issue by TheSmilingTurtle** [MM2-0/Kvaesitso#896] opened 2024-06-24 14:46 UTC
It is weird, but the keyboard crashes when i try to change the language while searching things in kvaesito, it does not happen elsewhere.

https://github.com/MM2-0/Kvaesitso/assets/59168627/2b969c13-ecbf-432b-8855-3b03503ddfb5

I am using Heliboard, a derrivative of the AOSP Keyboard and i have verified that this also happens with Gboard.

**Comment by MM2-0** [comment] 2024-06-24 14:51
Duplicate of #841

**Closed by MM2-0** 2024-06-24 14:51 UTC
