### ISSUE TITLE
App Crashes On Lanscape

### ISSUE THREAD

**Issue by stoponerr** [MM2-0/Kvaesitso#49] opened 2022-03-29 00:01 UTC
Running a community provided LineageOS port, fixing the issue may be up to the maintainer of that, but even still the ability to lock Kvæsitso to portrait mode would be nice.

> 
> java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.os.Bundle instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x3. Make sure other views do not use the same id.
> 	at android.view.View.onRestoreInstanceState(View.java:20771)
> 	at android.view.View.dispatchRestoreInstanceState(View.java:20743)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3986)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
> 	at android.view.View.restoreHierarchyState(View.java:20721)
> 	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2183)
> 	at android.app.Activity.onRestoreInstanceState(Activity.java:1679)
> 	at android.app.Activity.performRestoreInstanceState(Activity.java:1632)
> 	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1356)
> 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3473)
> 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
> 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
> 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:223)
> 	at android.app.ActivityThread.main(ActivityThread.java:7664)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

> APP.VERSION : 1.7.1-20220324 APP.VERSIONCODE : 2022032400 LAUNCHER.APP : android TIMEZONE : America/New_York VERSION.RELEASE : 11 VERSION.INCREMENTAL : eng.user.20220319.093803 VERSION.SDK.NUMBER : 30 BOARD : exynos9810 BOOTLOADER : N960FXXU9FUK2 BRAND : samsung CPU_ABI : arm64-v8a CPU_ABI2 : DISPLAY : lineage_crownlte-userdebug 11 RQ3A.211001.001 eng.user.20220319.093803 test-keys FINGERPRINT : samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXU6FTK1:user/release-keys HARDWARE : samsungexynos9810 HOST : DESKTOP-7MLK2RH ID : RQ3A.211001.001 MANUFACTURER : samsung MODEL : SM-N960F PRODUCT : crownltexx TAGS : test-keys TIME : 1647697029000 TYPE : userdebug

**Comment by MM2-0** [comment] 2022-03-29 10:46
This seems to be a duplicate of #47 , however I haven't found a way to reproduce this yet. Does it crash reliably every time you rotate the screen or only in some cases? Also, since the widgets are currently the main suspect, could you please provide a list of widgets you currently have added to your home screen?

**Closed** 2022-06-12 17:27 UTC
