### ISSUE TITLE
out of memory error log while charging the phone by night

### ISSUE THREAD

**Issue by RoiArthurB** [MM2-0/Kvaesitso#1001] opened 2024-07-28 01:54 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

I was sleeping by night and my phone was charging, and I saw this error message while waking up. I was not using my phone to create this bug 🤷

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 134217736 byte allocation with 100646912 free bytes and 122MB until OOM, target footprint 240614104, growth limit 268435456
	at androidx.collection.MutableScatterSet.initializeStorage(ScatterSet.kt:62)
	at androidx.collection.MutableScatterSet.resizeStorage(ScatterSet.kt:9)
	at androidx.collection.MutableScatterSet.findAbsoluteInsertIndex(ScatterSet.kt:177)
	at androidx.collection.MutableScatterSet.add(ScatterSet.kt:3)
	at androidx.collection.MutableScatterSet$MutableSetWrapper.add(ScatterSet.kt:3)
	at androidx.compose.runtime.ComposerImpl.updateRememberedValue(Composer.kt:165)
	at androidx.compose.runtime.EffectsKt.DisposableEffect(Effects.kt:4)
	at de.mm20.launcher2.ui.launcher.transitions.EnterHomeTransitionHandlerKt.HandleEnterHomeTransition(EnterHomeTransitionHandler.kt:53)
	at de.mm20.launcher2.ui.launcher.search.common.grid.GridItemKt.GridItem(GridItem.kt:475)
	at de.mm20.launcher2.ui.launcher.search.common.grid.SearchResultGridKt$SearchResultGrid$3.invoke(SearchResultGrid.kt:349)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:30)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$5.invoke(AnimatedContent.kt:132)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:20)
[32 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Ho_Chi_Minh<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : eng.root.20240701.214524<br>VERSION.SDK.NUMBER : 34<br>BOARD : kona<br>BOOTLOADER : unknown<br>BRAND : POCO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : lineage_alioth-userdebug 14 AP2A.240605.024 eng.root.20240701.214524 dev-keys<br>FINGERPRINT : POCO/alioth_global/alioth:13/TKQ1.221114.001/V816.0.2.0.TKHMIXM:user/release-keys<br>HARDWARE : qcom<br>HOST : 7f46abd94658<br>ID : AP2A.240605.024<br>MANUFACTURER : Xiaomi<br>MODEL : M2012K11AG<br>PRODUCT : lineage_alioth<br>TAGS : dev-keys<br>TIME : 1719870323000<br>TYPE : userdebug

**Comment by MM2-0** [comment] 2024-10-20 15:53
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:53 UTC
