### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Jojoba24** [MM2-0/Kvaesitso#1004] opened 2024-07-29 05:52 UTC
## Description

Happened during the night while charging the phone. 

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4d91176, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : G965FXXUHFVG4<br>VERSION.SDK.NUMBER : 29<br>BOARD : exynos9810<br>BOOTLOADER : G965FXXUHFVG4<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : QP1A.190711.020.G965FXXUHFVG4<br>FINGERPRINT : samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUHFVG4:user/release-keys<br>HARDWARE : samsungexynos9810<br>HOST : SWDH4610<br>ID : QP1A.190711.020<br>MANUFACTURER : samsung<br>MODEL : SM-G965F<br>PRODUCT : star2ltexx<br>TAGS : release-keys<br>TIME : 1658367067000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-29 09:12
Duplicate of #967

**Closed by MM2-0** 2024-07-29 09:12 UTC
