### ISSUE TITLE
Search result crash

### ISSUE THREAD

**Issue by Chubukov-Aleksey** [MM2-0/Kvaesitso#983] opened 2024-07-24 14:19 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

Recently, apps in search results started duplicating, and even crash on specific search queries 

## Strack trace

```
java.lang.IllegalArgumentException: Key "shortcut-shortcut://de.szalkowski.activitylauncher/FilesActivity" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:146)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:34)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
[76 lines truncated]
```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Yerevan<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : V816.0.5.0.TKCMIXM<br>VERSION.SDK.NUMBER : 33<br>BOARD : veux<br>BOOTLOADER : unknown<br>BRAND : Redmi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TKQ1.221114.001 test-keys<br>FINGERPRINT : Redmi/veux_global/veux:13/TKQ1.221114.001/V816.0.5.0.TKCMIXM:user/release-keys<br>HARDWARE : qcom<br>HOST : pangu-build-component-system-302741-7xjx1-d8dvv-rlmxm<br>ID : TKQ1.221114.001<br>MANUFACTURER : Xiaomi<br>MODEL : 2201116SG<br>PRODUCT : veux_global<br>TAGS : release-keys<br>TIME : 1719836842000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-24 14:34
Duplicate of #962

**Closed by MM2-0** 2024-07-24 14:34 UTC
