### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by bottlerocketjonny** [MM2-0/Kvaesitso#940] opened 2024-07-10 21:05 UTC
Gradual build up of sluggish behaviour leading up until a crash. 

Version: 1.31.1
Device: Pixel 6

**Comment by bottlerocketjonny** [comment] 2024-07-10 21:06
```java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 376832 free bytes and 368KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.onSystemActionsChanged(AccessibilityService.java:3103)
	at android.accessibilityservice.IAccessibilityServiceClient$Stub.onTransact(IAccessibilityServiceClient.java:356)
	at android.os.Binder.execTransactInternal(Binder.java:1505)
	at android.os.Binder.execTransact(Binder.java:1444)```

**Comment by bottlerocketjonny** [comment] 2024-07-11 06:04
I've upgraded to 1.31.2 (I use fdroid) so maybe that will have fixed this? I know you mentioned an external library causing the issue.

**Comment by MM2-0** [comment] 2024-10-20 15:53
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:53 UTC
