### ISSUE TITLE
Crash detected, device rebooted before suddenly

### ISSUE THREAD

**Issue by eengnr** [MM2-0/Kvaesitso#239] opened 2023-01-28 14:40 UTC
## Description

My device suddenly rebooted, then Kvaesitso showed this crash after the reboot. Not sure if the reboot is related, but I have this sudden reboot at least once a day and don't know yet which app causes it...

## Strack trace

```
java.lang.IllegalStateException: Offset is unspecified
	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:29)
	at androidx.compose.ui.node.NodeCoordinator.fromParentPosition-MK-Hz9U(NodeCoordinator.kt:3)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:19)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
[63 lines truncated]
```

## Device info
APP.VERSION : 1.21.2<br>APP.VERSIONCODE : 2023012500<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 9325679<br>VERSION.SDK.NUMBER : 33<br>BOARD : oriole<br>BOOTLOADER : slider-1.2-9152140<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TQ1A.230105.002<br>FINGERPRINT : google/oriole/oriole:13/TQ1A.230105.002/9325679:user/release-keys<br>HARDWARE : oriole<br>HOST : abfarm-release-rbe-64-2004-0066<br>ID : TQ1A.230105.002<br>MANUFACTURER : Google<br>MODEL : Pixel 6<br>PRODUCT : oriole<br>TAGS : release-keys<br>TIME : 1669240123000<br>TYPE : user

**Comment by MM2-0** [comment] 2023-04-14 16:56
Duplicate of #81

**Closed by MM2-0** 2023-04-14 16:56 UTC
Labels: crash report
