### ISSUE TITLE
Widget scrolling doesn't work

### ISSUE THREAD

**Issue by sith6** [MM2-0/Kvaesitso#1009] opened 2024-07-31 22:20 UTC
Love the launcher. But scrolling within the widgets doesn't work (e.g. In calendar, or task app)

**Comment by exstntlmsnthrp** [comment] 2024-08-01 03:07
You have to use two fingers to enroll within widgets and the widget needs to support it, from what I understand. Tasks app scrolls fine for me.

**Comment by MM2-0** [comment] 2024-08-11 20:18
Duplicate of #274

**Closed by MM2-0** 2024-08-11 20:18 UTC
