### ISSUE TITLE
Apps are not hidden

### ISSUE THREAD

**Issue by MM2-0** [MM2-0/Kvaesitso#923] opened 2024-07-04 19:44 UTC
![20240704_211514.jpg](https://github.com/MM2-0/Kvaesitso/assets/95169974/3ce1c2e0-3e02-4af3-9e37-30ca79909ec4)

Question: I am not able to hide any apps anymore, or have I got something wrong? When I choose Show in "Never", I see a hidden badge on the app, but the app icon is still visible, how to hide the app?

This has been happening since v1.31.1.

Edit: Once I launch the app, the icon is properly hidden, is this a bug?

_Originally posted by @nonomino in https://github.com/MM2-0/Kvaesitso/discussions/920#discussioncomment-9960460_

**Comment by MM2-0** [comment] 2024-07-04 19:46
@nonomino Do these apps stay hidden after you launched an app? Do they only disappear once  you launch that specific app, or any app? And what happens when you set visibility to "search only"?

**Comment by nonomino** [comment] 2024-07-05 01:00
1. Yes, they stay hidden after launching the app just once.
2. Only the icon that was launched disappears.
3. Same buggy behaviour when set to "Search results only".
4. Searching for something doesn't affect app visibility, they stay visible after clearing the search.

[Logs](https://gist.github.com/nonomino/412847c944a77285d33390adb81d8edc)

**Comment by MM2-0** [comment] 2024-07-06 01:34
Does it work in the calendar widget?

**Comment by nonomino** [comment] 2024-07-06 16:55
Calendar widget works fine, no issues with it, the issue appears only on the Apps drawer.

**Comment by Doc-4** [comment] 2024-07-07 22:13
I have a similar, related bug; 
Using quick settings (the line of filters above the keyboard) to show hidden apps without entering text in the search bar, then closing the app drawer and opening it results in hidden apps still being shown but the toggle being off. (At this point, they hide again if you turn it on and off.)

**Comment by thornySoap** [comment] 2024-07-08 10:04
Since 1.31.2 apps aren't hidden anymore when they match a search query. In the complete list they are hidden as intended, but when searching for something, the hidden-items-icon in the search bar disappears and they are instead shown in the list.

**Comment by MM2-0** [comment] 2024-07-08 10:12
> Since 1.31.2 apps aren't hidden anymore when they match a search query. In the complete list they are hidden as intended, but when searching for something, the hidden-items-icon in the search bar disappears and they are instead shown in the list.

That's mostly a migration issue. I decided to migrate apps that were previously selected to be hidden as "search only", because I assumed that that is what most people intended, when they hid apps: to make them disappear from the app grid. You can hide them altogether by long pressing an app, selecting "Customize" > "Show in" > "Never".

**Comment by nonomino** [comment] 2024-07-09 12:03
> ![20240704_211514.jpg](https://github.com/MM2-0/Kvaesitso/assets/95169974/3ce1c2e0-3e02-4af3-9e37-30ca79909ec4)
> 
> Question: I am not able to hide any apps anymore, or have I got something wrong? When I choose Show in "Never", I see a hidden badge on the app, but the app icon is still visible, how to hide the app?
> 
> This has been happening since v1.31.1.
> 
> Edit: Once I launch the app, the icon is properly hidden, is this a bug?
> 
> _Originally posted by @nonomino in https://github.com/MM2-0/Kvaesitso/discussions/920#discussioncomment-9960460_

I think this issue happens only when upgrading, I tried it on a fresh installation (without restoring from a backup), the bug was gone.

**Comment by nonomino** [comment] 2024-07-15 15:53
The problem is reappearing again, it worked fine for a while, then I did some reorganisation, and apps aren't removed from the Grid, you have to launch/tap on icon at least lnce to change visibility. Happens on a fresh install, no migration.

@MM2-0 please look into it.

**Comment by MM2-0** [comment] 2024-07-18 16:47
Can you download the latest [nightly version](https://fdroid.mm20.de/app/de.mm20.launcher2.nightly), backup and restore your data from the release version, and see if the issue is still there?

**Comment by nonomino** [comment] 2024-07-20 15:16
Yup, the issue's still there, in v1.32.0-20240720-nightly 🙁, have other people reported the same problem? Or is it just me?

**Comment by Doc-4** [comment] 2024-07-20 17:02
I'm having the opposite problem on the latest stable release here:
https://github.com/MM2-0/Kvaesitso/issues/965

**Comment by nonomino** [comment] 2024-07-21 10:01
I did try on a fresh installation, no restore. It worked for a few hours, and then it went back to being buggy.

**Comment by MM2-0** [comment] 2024-07-22 13:01
> I did try on a fresh installation, no restore. It worked for a few hours, and then it went back to being buggy.

Did you change anything during that time? I wonder if there is a limit of apps you can hide until it stops working, or if it is purely based on time.

**Comment by nonomino** [comment] 2024-07-22 16:31
> > I did try on a fresh installation, no restore. It worked for a few hours, and then it went back to being buggy.
> 
> Did you change anything during that time? I wonder if there is a limit of apps you can hide until it stops working, or if it is purely based on time.

I think this MIGHT be happening due to changing visibility of a lot of apps one after the other. Let's say I have 700 user-apps installed (which I do), It works for apps starting with A, B, C, D, but stops from the letter E.

**Closed** 2024-07-22 16:37 UTC
Labels: bug

**Comment by nonomino** [comment] 2024-07-22 16:53
Cool! Thank you so much 💓  
Will check in the next nightly!
