### ISSUE TITLE
Uninitialized LayoutCoordinates

### ISSUE THREAD

**Issue by SeidenTraum** [MM2-0/Kvaesitso#919] opened 2024-07-03 14:33 UTC
## Description

I just opened the app list menu, scrolled a bit and then the the bug happened

## Strack trace

```
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.
	at androidx.compose.animation.SharedBoundsNode$measure$1.invoke(SharedContentNode.kt:73)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:7)
	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:5)
	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:9)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate$placeSelf$2.invoke(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.placeSelf-MLgxB_4$1(LayoutNodeLayoutDelegate.kt:104)
	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:35)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:41)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:44)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.31.1<br>APP.VERSIONCODE : 2024070100<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Sao_Paulo<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 1919<br>VERSION.SDK.NUMBER : 33<br>BOARD : ums9230_hulk<br>BOOTLOADER : unknown<br>BRAND : realme<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RMX3834export_13_A.39<br>FINGERPRINT : realme/RMX3834/RE5C9F:13/TP1A.220624.014/T.R4T2.1715083581:user/release-keys<br>HARDWARE : ums9230_hulk<br>HOST : Ubuntu-139-32<br>ID : TP1A.220624.014<br>MANUFACTURER : realme<br>MODEL : RMX3834<br>PRODUCT : RMX3834<br>TAGS : release-keys<br>TIME : 1715086713000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-03 19:33
Duplicate of #913

**Closed by MM2-0** 2024-07-03 19:33 UTC
