### ISSUE TITLE
App Crash on search

### ISSUE THREAD

**Issue by YuvaKrishnaSaiGadi** [MM2-0/Kvaesitso#971] opened 2024-07-22 03:35 UTC
## Description

App crashing on searching with random letters

## Strack trace

```
java.lang.IllegalArgumentException: Key "calendar-calendar://623" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:146)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:34)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
[76 lines truncated]
```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : G990B2XXS7GXF1<br>VERSION.SDK.NUMBER : 34<br>BOARD : lahaina<br>BOOTLOADER : G990B2XXS7GXF1<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.G990B2XXS7GXF1<br>FINGERPRINT : samsung/r9q2xxx/r9q:14/UP1A.231005.007/G990B2XXS7GXF1:user/release-keys<br>HARDWARE : qcom<br>HOST : NA <br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-G990B2<br>PRODUCT : r9q2xxx<br>TAGS : release-keys<br>TIME : 1717573607000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-22 12:14
Duplicate of #962

**Closed by MM2-0** 2024-07-22 12:14 UTC
