### ISSUE TITLE
Crash when returning to homescreen from app

### ISSUE THREAD

**Issue by ddbb07** [MM2-0/Kvaesitso#916] opened 2024-07-02 20:56 UTC
## Description

I got a crash when returning to the homscreen from an app, the device was in power saving mode at the time. I have no clue how to reproduce it.

## Strack trace

```
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.
	at androidx.compose.animation.SharedBoundsNode$measure$1.invoke(SharedContentNode.kt:73)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:7)
	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:5)
	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:9)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate$placeSelf$2.invoke(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.placeSelf-MLgxB_4$1(LayoutNodeLayoutDelegate.kt:104)
	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:35)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:41)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:44)
[21 lines truncated]
```

## Device info
APP.VERSION : 1.31.1<br>APP.VERSIONCODE : 2024070100<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Prague<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2024062700<br>VERSION.SDK.NUMBER : 34<br>BOARD : cheetah<br>BOOTLOADER : cloudripper-14.5-11677884<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 2024062700<br>FINGERPRINT : google/cheetah/cheetah:14/AP2A.240605.024/2024062700:user/release-keys<br>HARDWARE : cheetah<br>HOST : grapheneos<br>ID : AP2A.240605.024<br>MANUFACTURER : Google<br>MODEL : Pixel 7 Pro<br>PRODUCT : cheetah<br>TAGS : release-keys<br>TIME : 1719516874000<br>TYPE : user

**Comment by ddbb07** [comment] 2024-07-02 21:00
I'll close it if anyone thinks it's to vague and non reproducable. This is the first and only time it has happened.

**Comment by ddbb07** [comment] 2024-07-02 21:03
Probably a dup of #913, stacktrace looks the same.

**Comment by ddbb07** [comment] 2024-07-02 21:10
Probably a dup of #913, stacktrace looks the same.

**Comment by MM2-0** [comment] 2024-07-03 19:32
Duplicate of #913

**Closed by MM2-0** 2024-07-03 19:32 UTC
