### ISSUE TITLE
This launcher stucks a lot

### ISSUE THREAD

**Issue by Ali-Sid** [MM2-0/Kvaesitso#753] opened 2024-04-02 23:26 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.pm.LauncherApps.getShortcuts(LauncherApps.java:893)
	at de.mm20.launcher2.appshortcuts.AppShortcutRepositoryImpl$search$1$1$1.invokeSuspend(AppShortcutRepository.kt:79)
	at de.mm20.launcher2.appshortcuts.AppShortcutRepositoryImpl$search$1$1$1.invoke(AppShortcutRepository.kt:13)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:44)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:18)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:26)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:102)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:187)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112)
[7 lines truncated]
```

## Device info
APP.VERSION : 1.28.0<br>APP.VERSIONCODE : 2023101300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : V12.5.1.0.QFGINXM<br>VERSION.SDK.NUMBER : 29<br>BOARD : sdm660<br>BOOTLOADER : unknown<br>BRAND : xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : QKQ1.190910.002 V12.5.1.0.QFGINXM<br>FINGERPRINT : xiaomi/lavender/lavender:10/QKQ1.190910.002/V12.5.1.0.QFGINXM:user/release-keys<br>HARDWARE : qcom<br>HOST : c4-miui-ota-bd172.bj<br>ID : QKQ1.190910.002<br>MANUFACTURER : Xiaomi<br>MODEL : Redmi Note 7S<br>PRODUCT : lavender<br>TAGS : release-keys<br>TIME : 1632320093000<br>TYPE : user

**Comment by summoner001** [comment] 2024-04-30 10:59
I can confirm. It keeps doing that to me.

**Comment by MM2-0** [comment] 2024-05-17 19:08
Duplicate of #546

**Closed by MM2-0** 2024-05-17 19:08 UTC
Labels: duplicate
