### ISSUE TITLE
App menu widget

### ISSUE THREAD

**Issue by TimoLS9921** [MM2-0/Kvaesitso#608] opened 2023-11-04 10:49 UTC
The ability to add a build-in widget with a specific category in it. A toggle to show or hide the name of the category would be nice.

The widget would look exactly the same as the favorites widget but would be separate instead of the tag being part of the favorites widget.

**Comment by MM2-0** [comment] 2023-11-04 11:02
Duplicate of #293

**Closed by MM2-0** 2023-11-04 11:02 UTC
