### ISSUE TITLE
Error while using the application

### ISSUE THREAD

**Issue by LeonelRFF** [MM2-0/Kvaesitso#1005] opened 2024-07-30 20:15 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.settings.searchactions.SearchActionsSettingsScreenKt$SearchActionsSettingsScreen$1$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:5)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[61 lines truncated]
```

## Device info
APP.VERSION : 1.32.1<br>APP.VERSIONCODE : 2024072200<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/Argentina/Buenos_Aires<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S.18b42c3-bd0a-110b46<br>VERSION.SDK.NUMBER : 34<br>BOARD : bengal<br>BOOTLOADER : unknown<br>BRAND : OPPO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CPH2363_14.0.0.710(EX01)<br>FINGERPRINT : OPPO/CPH2363/OP533FL1:14/TP1A.220905.001/S.18b42c3-bd0a-110b46:user/release-keys<br>HARDWARE : qcom<br>HOST : dg02-pool06-kvm20<br>ID : TP1A.220905.001<br>MANUFACTURER : OPPO<br>MODEL : CPH2363<br>PRODUCT : CPH2363<br>TAGS : release-keys<br>TIME : 1719239570000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-08-11 20:14
Duplicate of #937

**Closed by MM2-0** 2024-08-11 20:14 UTC
