### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by Piyu-Pika** [MM2-0/Kvaesitso#1100] opened 2024-09-28 04:41 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: User 999 is not a profile
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2378)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.os.IUserManager$Stub$Proxy.requestQuietModeEnabled(IUserManager.java:3249)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:3729)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:3714)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:3681)
	at de.mm20.launcher2.profiles.ProfileManager$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:1)
	at de.mm20.launcher2.ui.launcher.search.SearchColumnKt$SearchColumn$1$$ExternalSyntheticLambda15.invoke(R8$$SyntheticClass:46)
	at de.mm20.launcher2.ui.launcher.search.apps.AppResultsKt$AppResults$1$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:20)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
[69 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : 231010V791<br>VERSION.SDK.NUMBER : 30<br>BOARD : TECNO-KG8<br>BOOTLOADER : unknown<br>BRAND : TECNO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : KG8-H698CDEFGH-R-GL-231010V791<br>FINGERPRINT : TECNO/KG8-GL/TECNO-KG8:11/RP1A.200720.011/231010V791:user/release-keys<br>HARDWARE : mt6769<br>HOST : buildsrv-n26<br>ID : RP1A.200720.011<br>MANUFACTURER : TECNO MOBILE LIMITED<br>MODEL : TECNO KG8<br>PRODUCT : KG8-GL<br>TAGS : release-keys<br>TIME : 1696938415000<br>TYPE : user

**Comment by summoner001** [comment] 2024-10-12 07:11
Try to turn off: „Search on OpenStreetMap” // Settings > Search > Locations > OpenStreetMap
Its work for me.

**Comment by MM2-0** [comment] 2024-10-20 15:56
Duplicate of #1063

**Closed by MM2-0** 2024-10-20 15:56 UTC
