### ISSUE TITLE
[BUG] Badges for Suspended Apps (Random Inconsistancy)

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [MM2-0/Kvaesitso#776] opened 2024-04-22 11:14 UTC
#### Bug
hey @MM2-0 The badges for suspended app didn't work properly and are very inconsistent. Also if you click on a icon/app which has a suspend badge, the android will give you a popup that the **App isn't available** (Unpause app and OK) so that you can choose if you want to unpause it or not, but the launcher removes the badge as soon as we tap the icon (before the selection) and then if we choose not to Unpause it, the badge doesn't return annd launcher shows it that way.......

#### Feature Request
Also it'll be great if the launcher can have an option to choose between the badge & Gray Icon. As badge really looks very good and asthetic (i don't want to loose suspend badge) but it'll be a nice option to have if the suspended icons can be grayed out to, As it is like this in almost all the launchers, so it'll be more familliar in looks.

**Comment by Bhardwaj10Ankit** [comment] 2024-05-19 17:12
@MM2-0 🔔

**Comment by MM2-0** [comment] 2024-05-23 19:48
Duplicate of #746

**Closed by MM2-0** 2024-05-23 19:48 UTC
