### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by aiyagari** [MM2-0/Kvaesitso#1151] opened 2024-12-02 00:56 UTC
## Description

Nothing really, just using apps, not even home screen

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 2520320 free bytes and 2461KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(GraphicsLayerOwnerLayer.android.kt:33)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.mapBounds(GraphicsLayerOwnerLayer.android.kt:23)
	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:74)
	at androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf(NodeCoordinator.kt:79)
	at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:31)
	at androidx.compose.ui.semantics.SemanticsNode.getBoundsInWindow(SemanticsNode.kt:19)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:60)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:56)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:56)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:80)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.setTraversalValues(AndroidComposeViewAccessibilityDelegateCompat.android.kt:43)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes(AndroidComposeViewAccessibilityDelegateCompat.android.kt:40)
[12 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Los_Angeles<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S928U1UES4AXJA<br>VERSION.SDK.NUMBER : 34<br>BOARD : pineapple<br>BOOTLOADER : S928USQS4AXJA<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.S928U1UES4AXJA<br>FINGERPRINT : samsung/e3quew/e3q:14/UP1A.231005.007/S928U1UES4AXJA:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DJ6A02<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-S928U1<br>PRODUCT : e3quew<br>TAGS : release-keys<br>TIME : 1729833327000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-12-02 07:10
Duplicate of #1059

**Closed by MM2-0** 2024-12-02 07:10 UTC
