### ISSUE TITLE
Crash when searching

### ISSUE THREAD

**Issue by bgainor** [MM2-0/Kvaesitso#972] opened 2024-07-22 13:59 UTC
### Description
When searching for certain strings, Kvaesitso gets an IllegalArgumentException and exits due to a key being reused. I'm pasting in the stack trace from one particular crash, but I will note that I've gotten this same error for multiple search strings, with the particular key string in the stack trace differing in different circumstances. I'll also note that I just updated to 1.32.0 with F-Droid a few days ago; I didn't start getting the error until today, but it could still be that the new version introduced a bug. As a workaround, I turned off both "App shortcuts" and "Calendar" in my search settings, and so far that seems to have stopped this from occurring.

## Stack trace
```
java.lang.IllegalArgumentException: Key "calendar-calendar://14695" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:146)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:34)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:107)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:18)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:18)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:8)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:140)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:80)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:34)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:11)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7886)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:970)
```
## Device Information
```
APP.VERSION : 1.32.0
APP.VERSIONCODE : 2024071900
LAUNCHER.app : android
TIMEZONE : America/New_York
VERSION.RELEASE : 11
VERSION.INCREMENTAL : cc8087
VERSION.SDK.NUMBER : 30
BOARD : kiev
BOOTLOADER : MBM-3.0-kiev_retail-c451b161f40-230306
BRAND : motorola
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : RZKS31.Q3-45-16-8-19
FINGERPRINT : motorola/kiev_retailu/kiev:11/RZKS31.Q3-45-16-8-19/cc8087:user/release-keys
HARDWARE : qcom
HOST : ilclbld163
ID : RZKS31.Q3-45-16-8-19
MANUFACTURER : motorola
MODEL : motorola one 56 ace
PRODUCT : kiev_retailu
TAGS : release-keys
TIME : 1678095555000
TYPE : user
```

**Comment by MM2-0** [comment] 2024-07-22 14:00
Duplicate of #962

**Closed by MM2-0** 2024-07-22 14:00 UTC
