### ISSUE TITLE
crashing and returning to the default launcher! 

### ISSUE THREAD

**Issue by super-DG** [MM2-0/Kvaesitso#325] opened 2023-04-05 14:24 UTC
Sometimes when i unlock my phone it opens to the default launcher. But after I open the kvaesitso launcher app and close it from recent apps, the home becomes kvaesitso. Sometimes the default home app changes to the system launcher. Model: RMX2027 brand: Realme.
Something came up in my notification;
java.lang.IllegalStateException: Offset is unspecified
	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:29)
	at androidx.compose.ui.node.NodeCoordinator.fromParentPosition-MK-Hz9U(NodeCoordinator.kt:3)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:19)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
	at androidx.compose.ui.node.NodeCoordinator.localPositionOf-R5De75A(NodeCoordinator.kt:42)
	at androidx.compose.ui.node.NodeCoordinator.windowToLocal-MK-Hz9U(NodeCoordinator.kt:29)
	at androidx.compose.foundation.text.selection.TextFieldSelectionManagerKt.isSelectionHandleInVisibleBound(TextFieldSelectionManager.kt:27)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$onPositionedModifier$1.invoke(CoreTextField.kt:92)
	at androidx.compose.ui.layout.OnGloballyPositionedModifierImpl.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
	at androidx.compose.ui.node.BackwardsCompatNode.onGloballyPositioned(BackwardsCompatNode.kt:10)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:51)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:79)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:79)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:79)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:79)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:79)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:68)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:26)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:21)
	at android.view.View.draw(View.java:22782)
	at android.view.View.updateDisplayListIfDirty(View.java:21587)
	at android.view.View.draw(View.java:22480)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4644)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4378)
	at android.view.View.updateDisplayListIfDirty(View.java:21578)
	at android.view.View.draw(View.java:22480)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4644)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4378)
	at android.view.View.updateDisplayListIfDirty(View.java:21578)
	at android.view.View.draw(View.java:22480)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4644)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4378)
	at android.view.View.updateDisplayListIfDirty(View.java:21578)
	at android.view.View.draw(View.java:22480)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4644)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4378)
	at android.view.View.updateDisplayListIfDirty(View.java:21578)
	at android.view.View.draw(View.java:22480)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4644)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4378)
	at android.view.View.updateDisplayListIfDirty(View.java:21578)
	at android.view.View.draw(View.java:22480)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4644)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4378)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:2975)
	at android.view.View.draw(View.java:22782)
	at com.android.internal.policy.DecorView.draw(DecorView.java:901)
	at android.view.View.updateDisplayListIfDirty(View.java:21587)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4664)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4375)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3585)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2340)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9057)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1040)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:791)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by MM2-0** [comment] 2023-04-14 16:53
Duplicate of #81

**Closed by MM2-0** 2023-04-14 16:53 UTC
Labels: crash report
