### ISSUE TITLE
The manual icon tool is bad

### ISSUE THREAD

**Issue by Areg472** [MM2-0/Kvaesitso#800] opened 2024-05-07 13:20 UTC
So I like to manually change my icons, but the icon selector doesn't show all the icons of an icon pack

**Comment by derei** [comment] 2024-05-10 08:20
I can confirm this. I'm using Arcticons and Kvaesitso manual icon edit can't find a lot of icons, especially variants. I tried inputting the name as is in Arcticons, but no result was displayed.

**Comment by MM2-0** [comment] 2024-05-17 19:53
Duplicate of #757

**Closed by MM2-0** 2024-05-17 19:53 UTC
Labels: duplicate
