### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by VlaK0r** [MM2-0/Kvaesitso#1023] opened 2024-08-08 10:44 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.component.preferences.PreferenceScreenKt$PreferenceScreen$3$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:5)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[62 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Moscow<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 104.2.0.145C10<br>VERSION.SDK.NUMBER : 31<br>BOARD : FOA<br>BOOTLOADER : unknown<br>BRAND : HUAWEI<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : FOA-L29 14.2.0.145(C10E2R3P2)<br>FINGERPRINT : HUAWEI/FOA-L29/HWFOA-Q:12/HUAWEIFOA-LX9/104.2.0.145C10:user/release-keys<br>HARDWARE : qcom<br>HOST : cn-central-hcd-2a-1c10a439e1719469630865-bfc88687c-pm2vp<br>ID : HUAWEIFOA-LX9<br>MANUFACTURER : HUAWEI<br>MODEL : FOA-LX9<br>PRODUCT : FOA-L29<br>TAGS : release-keys<br>TIME : 1719474205000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-08-11 20:14
Duplicate of #937

**Closed by MM2-0** 2024-08-11 20:14 UTC
