### ISSUE TITLE
Sony xperia 1 iii, crash

### ISSUE THREAD

**Issue by Zion158** [MM2-0/Kvaesitso#1027] opened 2024-08-12 07:18 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.component.preferences.PreferenceScreenKt$PreferenceScreen$3$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:5)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[61 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Jerusalem<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 061002A0000472A0046651803<br>VERSION.SDK.NUMBER : 33<br>BOARD : lahaina<br>BOOTLOADER : xboot<br>BRAND : Sony<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 61.2.A.0.472A release-keys<br>FINGERPRINT : Sony/XQ-BC62/XQ-BC62:13/61.2.A.0.472A/061002A0000472A0046651803:user/release-keys<br>HARDWARE : qcom<br>HOST : BuildHost<br>ID : 61.2.A.0.472A<br>MANUFACTURER : Sony<br>MODEL : XQ-BC62<br>PRODUCT : XQ-BC62<br>TAGS : release-keys<br>TIME : 1692775759000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-08-12 12:04
Duplicate of #937

**Closed by MM2-0** 2024-08-12 12:04 UTC
