### ISSUE TITLE
[Feature Request] Having multiple widgets on the same row

### ISSUE THREAD

**Issue by c0mplexx92** [MM2-0/Kvaesitso#894] opened 2024-06-24 10:18 UTC
So I have a few widgets that are half or less width of the screen so it would be nice to have 2 or more in the same row as opposed to a small widget taking an entire line or expanding it and having lots of empty space

**Comment by MM2-0** [comment] 2024-06-24 14:50
Duplicate of #380

**Closed by MM2-0** 2024-06-24 14:50 UTC
