### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by SecretDerped** [MM2-0/Kvaesitso#1152] opened 2024-12-03 06:42 UTC
## Description

- The program has been running for a week without interruption since the last reboot of the device. Later, I noticed a decrease in performance and lags. After a while, the application rebooted with an OOM error. Lags has gone for now.
- I have 5 widgets on the home screen and a double-tap gesture that brings up the notification menu from above

## Stack trace
```
java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 2178560 free bytes and 2127KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3$1.create(RepeatOnLifecycle.kt:1)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:17)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:93)
	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3.invokeSuspend(RepeatOnLifecycle.kt:53)
	at androidx.lifecycle.RepeatOnLifecycleKt$repeatOnLifecycle$3.invoke(RepeatOnLifecycle.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:16)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:10)
	at androidx.lifecycle.RepeatOnLifecycleKt.repeatOnLifecycle(RepeatOnLifecycle.kt:3)
	at androidx.lifecycle.compose.FlowExtKt$collectAsStateWithLifecycle$1$1.invokeSuspend(FlowExt.kt:45)
	at androidx.lifecycle.compose.FlowExtKt$collectAsStateWithLifecycle$1$1.invoke(FlowExt.kt:13)
	at androidx.compose.runtime.SnapshotStateKt__ProduceStateKt$produceState$5$1.invokeSuspend(ProduceState.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@b21e95b, androidx.compose.runtime.BroadcastFrameClock@9ec45f8, StandaloneCoroutine{Cancelling}@cbb8ad1, AndroidUiDispatcher@ecbf936]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Moscow<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : T.121be63-1-166c9<br>VERSION.SDK.NUMBER : 33<br>BOARD : kalama<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : PJA110_13.1.1.302(CN01)<br>FINGERPRINT : OnePlus/PJA110/OP5943L1:13/TP1A.220905.001/T.121be63-1-166c9:user/release-keys<br>HARDWARE : qcom<br>HOST : dg02-pool03-kvm84<br>ID : TP1A.220905.001<br>MANUFACTURER : OnePlus<br>MODEL : PJA110<br>PRODUCT : PJA110<br>TAGS : release-keys<br>TIME : 1690035718000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-12-20 12:46
Duplicate of #1059

**Closed by MM2-0** 2024-12-20 12:46 UTC
