### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by vikasgola** [MM2-0/Kvaesitso#1111] opened 2024-10-18 09:10 UTC
## Description

Looks like memory is leaking somewhere which is causing launcher to crash after some time.

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 72 byte allocation with 413520 free bytes and 403KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at java.lang.Object.internalClone(Native Method)
	at java.lang.Object.clone(Object.java:267)
	at com.android.i18n.timezone.ZoneInfoData.getTransitions(ZoneInfoData.java:825)
	at libcore.util.ZoneInfo.<init>(ZoneInfo.java:149)
	at libcore.util.ZoneInfo.clone(ZoneInfo.java:303)
	at java.util.TimeZone.getDefault(TimeZone.java:703)
	at java.util.Calendar.defaultTimeZone(Calendar.java:1703)
	at java.util.Calendar.getInstance(Calendar.java:1642)
	at de.mm20.launcher2.calendar.providers.AndroidCalendarProvider$search$results$1.invokeSuspend(AndroidCalendarProvider.kt:309)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
[2 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2409041634<br>VERSION.SDK.NUMBER : 34<br>BOARD : Spacewar<br>BRAND : Nothing<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : U2.6-240904-1634<br>FINGERPRINT : Nothing/Spacewar/Spacewar:14/UP1A.231005.007/2409041634:user/release-keys<br>HARDWARE : qcom<br>MANUFACTURER : Nothing<br>MODEL : A063<br>PRODUCT : Spacewar<br>TAGS : release-keys<br>TIME : 1725438851000<br>TYPE : user

**Comment by vikasgola** [comment] 2024-10-18 09:13
It is also causing the launcher to get slow. On switching to the home page of the launcher every widget and app takes a bit to get loaded.

**Comment by MM2-0** [comment] 2024-10-20 15:53
Duplicate of #1059

**Closed by MM2-0** 2024-10-20 15:53 UTC
