### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by FedeB97** [MM2-0/Kvaesitso#1184] opened 2024-12-21 20:45 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Stack trace

```
java.lang.NullPointerException
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invokeSuspend(IconService.kt:214)
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invoke(IconService.kt:28)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:252)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:24)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:79)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:30)
	at kotlinx.coroutines.flow.internal.SubscriptionCountStateFlow.increment(AbstractSharedFlow.kt:44)
	at kotlinx.coroutines.flow.internal.AbstractSharedFlow.allocateSlot(AbstractSharedFlow.kt:81)
[23 lines truncated]
```

## Device info
APP.VERSION : 1.34.0-fdroid<br>APP.VERSIONCODE : 2024120500<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/Argentina/La_Rioja<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : f73e35-2bfcf<br>VERSION.SDK.NUMBER : 33<br>BOARD : hawao<br>BOOTLOADER : MBM-3.0-hawao_g-8847829342a-241120<br>BRAND : motorola<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : T2SES33.73-23-2-12<br>FINGERPRINT : motorola/hawao_g/hawao:13/T2SES33.73-23-2-12/f73e35-2bfcf:user/release-keys<br>HARDWARE : qcom<br>HOST : ilclbld198<br>ID : T2SES33.73-23-2-12<br>MANUFACTURER : motorola<br>MODEL : moto g42<br>PRODUCT : hawao_g<br>TAGS : release-keys<br>TIME : 1732085475000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-12-23 15:14
Duplicate of #1181

**Closed by MM2-0** 2024-12-23 15:14 UTC
