### ISSUE TITLE
Alarm Countdown is using the wrong unit

### ISSUE THREAD

**Issue by ax4w** [MM2-0/Kvaesitso#1112] opened 2024-10-18 17:00 UTC
I have an alarm in 3 days:
![Screenshot_20241018_185906_Clock.jpg](https://github.com/user-attachments/assets/665dbcd6-f209-41b3-b798-8d96e4fe4b0f)

But the laucher says 3 hours:
![Screenshot_20241018_185902_Kvaesitso.jpg](https://github.com/user-attachments/assets/725f15c2-a206-48a3-9b07-bcf7454a7cb8)

**Comment by MM2-0** [comment] 2024-10-20 15:58
Duplicate of #172

**Closed by MM2-0** 2024-10-20 15:58 UTC
