### ISSUE TITLE
asking everytime to select launcher after unlocking

### ISSUE THREAD

**Issue by tapas-2000** [MM2-0/Kvaesitso#974] opened 2024-07-22 18:38 UTC
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5624707, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : A528BXXS9GXF8<br>VERSION.SDK.NUMBER : 34<br>BOARD : lahaina<br>BOOTLOADER : A528BXXS9GXF8<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.A528BXXS9GXF8<br>FINGERPRINT : samsung/a52sxqxx/a52sxq:14/UP1A.231005.007/A528BXXS9GXF8:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DKGA12<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-A528B<br>PRODUCT : a52sxqxx<br>TAGS : release-keys<br>TIME : 1719197981000<br>TYPE : user

**Comment by MM2-0** [comment] 2024-07-22 18:41
Duplicate of #967

**Closed by MM2-0** 2024-07-22 18:41 UTC
